# Generated by Django 4.1.2 on 2022-11-06 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NotSet'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Fatal')], db_index=True, default=40, verbose_name='Seviye'),
        ),
        migrations.AlterField(
            model_name='log',
            name='logger_name',
            field=models.CharField(max_length=100, verbose_name='Loglayıcı Adı'),
        ),
        migrations.AlterField(
            model_name='log',
            name='msg',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='log',
            name='trace',
            field=models.TextField(blank=True, null=True, verbose_name='Yığın'),
        ),
    ]
