# Generated by Django 4.1.2 on 2022-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_state_name_alter_task_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Durum'),
        ),
    ]
