# Generated by Django 4.1.2 on 2022-11-14 07:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_state_created_date_state_description_state_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Renk'),
        ),
    ]
