# Generated by Django 4.1.3 on 2022-11-29 07:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_state_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='state',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Renk'),
        ),
    ]
